### ISSUE TITLE
RuntimeError: The size of tensor a (20) must match the size of tensor b (2) at non-singleton dimension 0

### ISSUE THREAD

**Issue by DarkAlchy** [Bikecicle/LoRAW#15]
It almost worked.

Generating demo
Getting conditioning
/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/training/diffusion.py:506: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():
Generating demo for cfg scale 4
/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/training/diffusion.py:528: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():
                                                                                                                                   /mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/inference/sampling.py:61: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():
  0%|                                                                                                       | 0/250 [00:00<?, ?it/s]
RuntimeError: The size of tensor a (20) must match the size of tensor b (2) at non-singleton dimension 0
Traceback (most recent call last):
  File "/mnt/Win_D/LoRAW/train.py", line 174, in <module>
    main()
  File "/mnt/Win_D/LoRAW/train.py", line 171, in main
    trainer.fit(training_wrapper, train_dl, ckpt_path=args.ckpt_path if args.ckpt_path else None)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 259, in advance
    call._call_callback_hooks(trainer, "on_train_batch_end", batch_output, batch, batch_idx)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/training/diffusion.py", line 559, in on_train_batch_end
    raise e
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/training/diffusion.py", line 532, in on_train_batch_end
    fakes = sample(model, noise, self.demo_steps, 0, **cond_inputs, cfg_scale=cfg_scale, batch_cfg=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/inference/sampling.py", line 62, in sample
    v = model(x, ts * t[i], **extra_args).float()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/models/diffusion.py", line 532, in forward
    return self.model(
           ^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/models/dit.py", line 334, in forward
    batch_output = self._forward(
                   ^^^^^^^^^^^^^^
  File "/mnt/Win_D/LoRAW/venv/lib/python3.11/site-packages/stable_audio_tools/models/dit.py", line 180, in _forward
    global_embed = global_embed + timestep_embed
                   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (20) must match the size of tensor b (2) at non-singleton dimension 0

**Comment by NeuralNotW0rk** [comment]
If I recall correctly, this is a Stable Audio Tools error if there's a mismatch between specified number of demos and actual number of prompts given in the model config.

For example, if I set `num_demos` to 4, I have to provide exactly 4 example prompts in `demo_cond`. Did you by chance set `num_demos` to 20 with only 2 prompts listed?

```
"demo": {
            "demo_every": 2000,
            "demo_steps": 250,
            "num_demos": 4,
            "demo_cond": [
                {"prompt": "Amen break 174 BPM", "seconds_start": 0, "seconds_total": 12},
                {"prompt": "A beautiful orchestral symphony, classical music", "seconds_start": 0, "seconds_total": 160},
                {"prompt": "Chill hip-hop beat, chillhop", "seconds_start": 0, "seconds_total": 190},
                {"prompt": "A pop song about love and loss", "seconds_start": 0, "seconds_total": 180}
            ],
            "demo_cfg_scales": [3, 6, 9]
        }
```

**Comment by DarkAlchy** [comment]
You are correct.  Thank you.
